// Regenerates the tool lists in README.md from the live aaaa.fyi API.
// Run: node generate.mjs   (also runs weekly via .github/workflows/update.yml)
import { readFileSync, writeFileSync } from "node:fs";

const API = "https://aaaa.fyi/api/listings";
const SITE = "https://aaaa.fyi";
const PATH = { skills:"skills", "mcp-servers":"mcp", plugins:"plugins", subagents:"subagents", workflows:"workflows", prompts:"prompts" };
const num = n => n==null ? "" : n>=1e6 ? (n/1e6).toFixed(1)+"M" : n>=1e3 ? Math.round(n/1e3)+"k" : (""+n);
const enc = s => s.split("/").map(encodeURIComponent).join("/");

async function top({ taxonomy, category, sort="installs", limit=15 }) {
  const u = new URL(API);
  u.searchParams.set("taxonomy", taxonomy);
  if (category) u.searchParams.set("category", category);
  u.searchParams.set("sort", sort);
  u.searchParams.set("limit", String(limit * 4));
  const j = await (await fetch(u)).json();
  const seen = new Set(), out = [];
  for (const t of j.items || []) {
    const key = t.repo || t.slug.split("/")[0];
    if (seen.has(key)) continue;
    seen.add(key); out.push(t);
    if (out.length >= limit) break;
  }
  return out;
}

const row = t => {
  const url = `${SITE}/${PATH[t.taxonomy]}/${enc(t.slug)}`;
  const stat = [t.downloads!=null ? num(t.downloads)+" installs" : "", t.stars ? num(t.stars)+"⭐" : ""].filter(Boolean).join(", ");
  const src = t.repo ? ` — [source](https://github.com/${t.repo})` : "";
  const d = (t.description||"").replace(/\|/g,"/").replace(/\s+/g," ").slice(0,110).trim();
  return `- **[${t.name}](${url})** ${stat?`(\`${stat}\`) `:""}— ${d}${src}`;
};

const SECTIONS = [
  { h:"🧠 Top Skills", taxonomy:"skills", limit:15, hub:"/skills" },
  { h:"🔌 Top MCP Servers", taxonomy:"mcp-servers", limit:15, hub:"/mcp" },
  { h:"🧩 Top Plugins", taxonomy:"plugins", sort:"stars", limit:10, hub:"/plugins" },
  { h:"🤖 Top Subagents", taxonomy:"subagents", sort:"stars", limit:10, hub:"/subagents" },
  { h:"⚙️ Top Workflows", taxonomy:"workflows", limit:8, hub:"/workflows" },
  { h:"💬 Top Prompts", taxonomy:"prompts", limit:8, hub:"/prompts" },
  { h:"👨‍💻 Best Coding Skills", taxonomy:"skills", category:"Coding", limit:10, hub:"/skills/c/coding" },
  { h:"🔐 Best Security Skills", taxonomy:"skills", category:"Security", limit:8, hub:"/skills/c/security" },
  { h:"📣 Best Marketing & SEO Skills", taxonomy:"skills", category:"Marketing", limit:8, hub:"/skills/c/marketing" },
  { h:"🎨 Best Design Skills", taxonomy:"skills", category:"Design", limit:8, hub:"/skills/c/design" },
  { h:"🧪 Best Testing Skills", taxonomy:"skills", category:"Testing", limit:8, hub:"/skills/c/testing" },
  { h:"📊 Best Data Skills", taxonomy:"skills", category:"Data", limit:8, hub:"/skills/c/data" },
  { h:"🗄️ Best Database MCP Servers", taxonomy:"mcp-servers", category:"Data", sort:"stars", limit:8, hub:"/mcp/c/data" },
  { h:"🛠️ Best DevTools MCP Servers", taxonomy:"mcp-servers", category:"DevTools", sort:"stars", limit:8, hub:"/mcp/c/devtools" },
  { h:"🚀 Best DevOps MCP Servers", taxonomy:"mcp-servers", category:"Infrastructure", sort:"stars", limit:8, hub:"/mcp/c/infrastructure" },
];

const parts = [];
for (const s of SECTIONS) {
  const items = await top(s);
  if (!items.length) continue;
  parts.push(`### ${s.h}\n\n${items.map(row).join("\n")}\n\n_→ [See all on aaaa.fyi](${SITE}${s.hub})_\n`);
}
const block = parts.join("\n");

const md = readFileSync("README.md", "utf8");
const START = "<!-- AUTOGEN:START -->", END = "<!-- AUTOGEN:END -->";
const out = md.replace(
  new RegExp(`${START}[\\s\\S]*${END}`),
  `${START}\n<!-- Do not edit by hand — regenerated by generate.mjs -->\n\n${block}\n${END}`,
);
writeFileSync("README.md", out);
console.log(`Regenerated ${SECTIONS.length} sections.`);
